fix: typo in CronDetector searchpath
quirrel-dev/quirrel pull request #1058
Opened 2022-10-20 06:13 UTC by boredland

I read up code on the CronDetector - found a typo and added a line more to the docs to make it easier for others to understand.

2022-10-20 06:14 UTC, boredland commented on docs/docs/deploying.md
> +:::note VERCEL*URL
this is so confusing. in my ide:

![image](https://user-images.githubusercontent.com/4662748/196870269-b2ba4c21-bb50-4a0e-9d4b-5e92c9990fa1.png)

2022-10-20 07:38 UTC, Skn0tt requested changes
good catch with the typo + lovely addition to docs, thank you :)

it looks like there are some things that your IDE changed with the markdown, please revert tose and reduce the changes to the typo + docs.

2022-10-21 09:02 UTC, boredland commented
it is confusing. the changes, it seems, are applied with an on-commit hook, not by vscode. however: I reverted them. how about that line-break it removed in the console statement. to me, now it looks less weird. but perhaps there is a reason you had it as it was?

2022-10-21 09:07 UTC, Skn0tt approved these changes
LGTM! weird that there was a commit hook 🤔

2022-10-21 09:07 UTC, merged